-- AlterTable
ALTER TABLE `Campaign` ADD COLUMN `failureReason` TEXT NULL,
    MODIFY `status` ENUM('DRAFT', 'SCHEDULED', 'SENDING', 'PAUSED', 'COMPLETED', 'CANCELLED', 'FAILED') NOT NULL DEFAULT 'DRAFT';

